name: Debug Release Event

on:
  release:
    types: [published, unpublished, created, edited, deleted, prereleased, released]

jobs:
  debug-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print event details
        run: |
          echo "Event: ${{ toJson(github.event) }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Prerelease: ${{ github.event.release.prerelease }}"
          echo "Draft: ${{ github.event.release.draft }}"
