name: PR CI

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read # for checkout

jobs:
  shared-ci:
    uses: ./.github/workflows/shared-ci.yml
    with:
      fetch-depth: 1
      run-audit-signatures: false
    secrets: inherit

  compressed-size:
    runs-on: ubuntu-latest
    needs: [shared-ci]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          cache: npm
      - name: Install dependencies
        run: npm clean-install
      - name: Build
        run: npm run build
      - name: Compressed size
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "./dist/*.{js,cjs}"
